<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="14" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="167" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="167" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
      <class name="com.PracticeFeb2020.Demo1">
        <test-method status="PASS" signature="test1()[pri:0, instance:com.PracticeFeb2020.Demo1@4c12331b]" name="test1" duration-ms="28" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.PracticeFeb2020.Demo1 -->
      <class name="com.PracticeFeb2020.Demo6">
        <test-method status="PASS" signature="test10()[pri:0, instance:com.PracticeFeb2020.Demo6@7586beff]" name="test10" duration-ms="5" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test10 -->
        <test-method status="PASS" signature="test11()[pri:0, instance:com.PracticeFeb2020.Demo6@7586beff]" name="test11" duration-ms="3" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test11 -->
        <test-method status="PASS" signature="test12()[pri:1, instance:com.PracticeFeb2020.Demo6@7586beff]" name="test12" duration-ms="5" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test12 -->
        <test-method status="FAIL" signature="test13()[pri:2, instance:com.PracticeFeb2020.Demo6@7586beff]" name="test13" duration-ms="3" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.PracticeFeb2020.Demo6.test13(Demo6.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test13 -->
        <test-method status="SKIP" signature="test14()[pri:3, instance:com.PracticeFeb2020.Demo6@7586beff]" name="test14" duration-ms="0" started-at="2020-02-06T19:52:50 EST" depends-on-methods="com.PracticeFeb2020.Demo6.test13, com.PracticeFeb2020.Demo6.test12" finished-at="2020-02-06T19:52:50 EST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo6.test14()[pri:3, instance:com.PracticeFeb2020.Demo6@7586beff] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo6.test14()[pri:3, instance:com.PracticeFeb2020.Demo6@7586beff] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test14 -->
      </class> <!-- com.PracticeFeb2020.Demo6 -->
      <class name="com.PracticeFeb2020.Demo3">
        <test-method status="PASS" signature="test3()[pri:0, instance:com.PracticeFeb2020.Demo3@3b69e7d1]" name="test3" duration-ms="3" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- com.PracticeFeb2020.Demo3 -->
      <class name="com.PracticeFeb2020.Demo2">
        <test-method status="PASS" signature="test2()[pri:0, instance:com.PracticeFeb2020.Demo2@815b41f]" name="test2" duration-ms="2" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.PracticeFeb2020.Demo2 -->
      <class name="com.PracticeFeb2020.Demo5">
        <test-method status="PASS" signature="test5()[pri:0, instance:com.PracticeFeb2020.Demo5@5542c4ed]" name="test5" duration-ms="2" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="test6()[pri:0, instance:com.PracticeFeb2020.Demo5@5542c4ed]" name="test6" duration-ms="2" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method status="PASS" signature="test7()[pri:0, instance:com.PracticeFeb2020.Demo5@5542c4ed]" name="test7" duration-ms="2" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
        <test-method status="PASS" signature="test8()[pri:0, instance:com.PracticeFeb2020.Demo5@5542c4ed]" name="test8" duration-ms="1" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test8 -->
        <test-method status="PASS" signature="test9()[pri:0, instance:com.PracticeFeb2020.Demo5@5542c4ed]" name="test9" duration-ms="2" started-at="2020-02-06T19:52:50 EST" depends-on-methods="com.PracticeFeb2020.Demo5.test6, com.PracticeFeb2020.Demo5.test7" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test9 -->
      </class> <!-- com.PracticeFeb2020.Demo5 -->
      <class name="com.PracticeFeb2020.Demo4">
        <test-method status="PASS" signature="test1()[pri:0, instance:com.PracticeFeb2020.Demo4@1573f9fc]" name="test1" duration-ms="1" started-at="2020-02-06T19:52:50 EST" finished-at="2020-02-06T19:52:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.PracticeFeb2020.Demo4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
